/* SPDX-License-Identifier: Apache-2.0 */
import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { defineCommand } from "citty";
import { loadSemanticLayer, renderGeneratedIndex } from "@arivie/semantic";
import { printCliCommandError } from "../lib/cli-errors.js";

interface RunOptions {
  semantic?: string;
  skills?: string;
  out?: string;
  cwd?: string;
}

function quoteLiteral(value: string): string {
  return `'${value.replace(/\\/g, "\\\\").replace(/'/g, "\\'")}'`;
}

function discoverSkillNames(skillsDir: string): string[] {
  if (!existsSync(skillsDir)) return [];
  const names: string[] = [];
  for (const entry of readdirSync(skillsDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const skillMd = join(skillsDir, entry.name, "SKILL.md");
    try {
      if (statSync(skillMd).isFile()) {
        names.push(entry.name);
      }
    } catch {
      // not a skill directory
    }
  }
  return names.sort();
}

function renderSkillsBlock(skillNames: string[]): string {
  if (skillNames.length === 0) {
    return [
      "export const skillNames = [] as const;",
      "export type SkillName = never;",
    ].join("\n");
  }
  return [
    `export const skillNames = [${skillNames.map(quoteLiteral).join(", ")}] as const;`,
    "export type SkillName = (typeof skillNames)[number];",
  ].join("\n");
}

/**
 * Generate `.arivie/types.ts` — a fresh file containing typed handles
 * for entity names, per-entity measures/dimensions/segments, the master
 * `ArivieSemantic` shape, and skill names. Run after editing
 * semantic/entities or skills so downstream code gets autocomplete +
 * type-narrowed references.
 *
 * Idempotent: rewrites the file in place; no other artifacts touched.
 */
export async function runTypesCommand(opts: RunOptions): Promise<number> {
  try {
    const cwd = opts.cwd ?? process.cwd();
    const semanticPath = resolve(cwd, opts.semantic ?? "./semantic");
    const skillsPath = resolve(cwd, opts.skills ?? "./skills");
    const outPath = resolve(cwd, opts.out ?? "./.arivie/types.ts");

    if (!existsSync(semanticPath)) {
      throw new Error(
        `arivie types: semantic directory not found at ${semanticPath}. Pass --semantic <path> if it lives elsewhere.`,
      );
    }

    const layer = await loadSemanticLayer(semanticPath);
    const entityBlock = renderGeneratedIndex(layer);

    const skillNames = discoverSkillNames(skillsPath);
    const skillsBlock = renderSkillsBlock(skillNames);

    const generatedAt = new Date().toISOString();
    const header = [
      "// @generated by `arivie types` — do not edit.",
      `// Generated at: ${generatedAt}`,
      `// Semantic dir: ${relative(cwd, semanticPath)}`,
      `// Skills dir:   ${relative(cwd, skillsPath)}`,
      "",
    ].join("\n");

    // Trim the per-block "@generated" prologue since we add a unified one.
    const entityBody = entityBlock
      .split("\n")
      .filter((line) => !line.startsWith("// @generated") && !line.startsWith("// Generated at:"))
      .join("\n")
      .replace(/^\n+/, "");

    const out = `${header}${entityBody}\n${skillsBlock}\n`;
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, out, "utf8");

    console.log(`arivie types: wrote ${relative(cwd, outPath)}`);
    console.log(`  entities: ${layer.entities.size}`);
    console.log(`  skills:   ${skillNames.length}`);
    return 0;
  } catch (err) {
    printCliCommandError("types", err);
    return 1;
  }
}

export const typesCommand = defineCommand({
  meta: {
    name: "types",
    description:
      "Generate .arivie/types.ts from semantic/entities/*.yml + skills/*/SKILL.md. " +
      "Emits typed handles for entity names, per-entity measures/dimensions/segments, " +
      "and skill names so downstream code gets autocomplete + narrowing.",
  },
  args: {
    semantic: {
      type: "string",
      description: "Semantic layer directory (default: ./semantic)",
    },
    skills: {
      type: "string",
      description: "Skills directory (default: ./skills)",
    },
    out: {
      type: "string",
      description: "Output file (default: ./.arivie/types.ts)",
    },
  },
  async run({ args }) {
    return await runTypesCommand({
      semantic: args.semantic as string | undefined,
      skills: args.skills as string | undefined,
      out: args.out as string | undefined,
    });
  },
});
