/* SPDX-License-Identifier: Apache-2.0 */
/* Auto-generated by scripts/inline-semantic.ts — do not edit by hand. */
/* Re-run via `pnpm --filter with-cloudflare-do build` (prebuild hook). */
import type { Entity, Catalog, SemanticLayer } from "@arivie/semantic";

const ENTITY_ENTRIES: readonly (readonly [string, Entity])[] = [
  [
    "customers",
    {
      "name": "customers",
      "description": "Customer accounts. One row per customer.\nUse for cohort and account-level reporting.\n",
      "grain": "one row per customer",
      "primary_key": "id",
      "source": {
        "adapter": "postgres",
        "instance": "primary"
      },
      "dimensions": [
        {
          "name": "email",
          "sql": "email",
          "type": "text",
          "description": "Primary contact email."
        },
        {
          "name": "created_at",
          "sql": "created_at",
          "type": "timestamp",
          "description": "When the customer account was created."
        },
        {
          "name": "country",
          "sql": "country",
          "type": "text",
          "description": "ISO country code for the billing address."
        }
      ],
      "joins": [
        {
          "to": "orders",
          "on": "customers.id = orders.customer_id",
          "type": "one_to_many"
        }
      ],
      "example_questions": [
        "How many new customers signed up last month?",
        "Which countries have the most customers?"
      ]
    }
  ],
  [
    "invoices",
    {
      "name": "invoices",
      "description": "Customer invoices for accounts receivable.\nRevenue recognition uses paid invoices; open invoices contribute to outstanding AR.\n",
      "grain": "one row per invoice",
      "primary_key": "id",
      "source": {
        "adapter": "postgres",
        "instance": "primary"
      },
      "measures": [
        {
          "name": "recognized_revenue",
          "description": "Revenue recognized from paid invoices in the period.",
          "sql": "SUM(amount) FILTER (WHERE status = 'paid')"
        },
        {
          "name": "open_balance",
          "description": "Unpaid invoice balance still outstanding.",
          "sql": "SUM(amount - amount_paid) FILTER (WHERE status IN ('sent', 'overdue'))"
        }
      ],
      "dimensions": [
        {
          "name": "status",
          "sql": "status",
          "values": [
            "draft",
            "sent",
            "paid",
            "overdue",
            "void"
          ],
          "description": "Invoice lifecycle status."
        },
        {
          "name": "issued_at",
          "sql": "issued_at",
          "type": "timestamp",
          "description": "When the invoice was issued."
        }
      ],
      "joins": [
        {
          "to": "customers",
          "on": "invoices.customer_id = customers.id",
          "type": "many_to_one"
        }
      ],
      "example_questions": [
        "What is recognized revenue from invoices this quarter?",
        "How much AR is overdue?"
      ],
      "example_queries": [
        {
          "question": "Recognized revenue this quarter",
          "sql": "SELECT SUM(amount) AS revenue\nFROM invoices\nWHERE status = 'paid'\n  AND issued_at >= date_trunc('quarter', CURRENT_DATE)\n"
        }
      ]
    }
  ],
  [
    "line_items",
    {
      "name": "line_items",
      "description": "Individual line items on orders. One row per product line on an order.\nJoin to products for SKU and category attributes.\n",
      "grain": "one row per line item",
      "primary_key": "id",
      "source": {
        "adapter": "postgres",
        "instance": "primary"
      },
      "dimensions": [
        {
          "name": "quantity",
          "sql": "quantity",
          "type": "numeric",
          "description": "Units ordered on this line."
        },
        {
          "name": "unit_price",
          "sql": "unit_price",
          "type": "numeric",
          "description": "Price per unit at time of order."
        }
      ],
      "joins": [
        {
          "to": "orders",
          "on": "line_items.order_id = orders.id",
          "type": "many_to_one"
        },
        {
          "to": "products",
          "on": "line_items.product_id = products.id",
          "type": "many_to_one"
        }
      ],
      "example_questions": [
        "What are the best-selling products by quantity?",
        "Average items per order last month?"
      ]
    }
  ],
  [
    "orders",
    {
      "name": "orders",
      "description": "Orders placed by customers. One row per order.\nFor revenue reporting, exclude cancelled and draft orders.\n",
      "grain": "one row per order",
      "primary_key": "id",
      "source": {
        "adapter": "postgres",
        "instance": "primary"
      },
      "measures": [
        {
          "name": "revenue",
          "description": "Total revenue from completed orders (excludes tax and shipping).",
          "sql": "SUM(total_amount) FILTER (WHERE status = 'completed')"
        },
        {
          "name": "outstanding_amount",
          "description": "Total unpaid order value across open orders.",
          "sql": "SUM(total_amount - amount_paid) FILTER (WHERE status NOT IN ('paid', 'void', 'draft'))"
        }
      ],
      "dimensions": [
        {
          "name": "status",
          "sql": "status",
          "values": [
            "pending",
            "processing",
            "completed",
            "refunded",
            "cancelled",
            "draft"
          ],
          "description": "Order lifecycle status. Use completed for revenue."
        },
        {
          "name": "created_at",
          "sql": "created_at",
          "type": "timestamp",
          "description": "When the order was placed. Use date_trunc() for grouping."
        },
        {
          "name": "currency",
          "sql": "currency",
          "description": "ISO currency code on the order (USD, EUR, GBP)."
        }
      ],
      "segments": [
        {
          "name": "current_quarter",
          "sql": "created_at >= date_trunc('quarter', CURRENT_DATE)",
          "description": "Orders placed in the current calendar quarter."
        }
      ],
      "joins": [
        {
          "to": "customers",
          "on": "orders.customer_id = customers.id",
          "type": "many_to_one"
        }
      ],
      "example_questions": [
        "What is my total revenue this quarter?",
        "How many orders did we get last month?"
      ],
      "example_queries": [
        {
          "question": "Total revenue this quarter",
          "sql": "SELECT SUM(total_amount) AS revenue\nFROM orders\nWHERE status = 'completed'\n  AND created_at >= date_trunc('quarter', CURRENT_DATE)\n"
        }
      ]
    }
  ],
  [
    "products",
    {
      "name": "products",
      "description": "Product catalog. One row per SKU.\nJoin target from line_items for category and pricing context.\n",
      "grain": "one row per product",
      "primary_key": "id",
      "source": {
        "adapter": "postgres",
        "instance": "primary"
      },
      "dimensions": [
        {
          "name": "sku",
          "sql": "sku",
          "type": "text",
          "description": "Stock keeping unit identifier."
        },
        {
          "name": "category",
          "sql": "category",
          "type": "text",
          "description": "Merchandising category (e.g. apparel, electronics)."
        },
        {
          "name": "list_price",
          "sql": "list_price",
          "type": "numeric",
          "description": "Current list price in the catalog."
        }
      ],
      "joins": [
        {
          "to": "line_items",
          "on": "products.id = line_items.product_id",
          "type": "one_to_many"
        }
      ],
      "example_questions": [
        "How many active products do we have?",
        "Products by category count?"
      ]
    }
  ]
] as const;

const CATALOG: Catalog = {
  "entities": [
    {
      "name": "customers",
      "description": "Customer accounts. One row per customer.\nUse for cohort and account-level reporting.\n",
      "keywords": [
        "customers"
      ]
    },
    {
      "name": "invoices",
      "description": "Customer invoices for accounts receivable.\nRevenue recognition uses paid invoices; open invoices contribute to outstanding AR.\n",
      "keywords": [
        "invoices"
      ]
    },
    {
      "name": "line_items",
      "description": "Individual line items on orders. One row per product line on an order.\nJoin to products for SKU and category attributes.\n",
      "keywords": [
        "line",
        "items"
      ]
    },
    {
      "name": "orders",
      "description": "Orders placed by customers. One row per order.\nFor revenue reporting, exclude cancelled and draft orders.\n",
      "keywords": [
        "orders"
      ]
    },
    {
      "name": "products",
      "description": "Product catalog. One row per SKU.\nJoin target from line_items for category and pricing context.\n",
      "keywords": [
        "products"
      ]
    }
  ],
  "generated_at": "2026-06-21T10:11:35.684Z",
  "source_files": [
    "entities/customers.yml",
    "entities/invoices.yml",
    "entities/line_items.yml",
    "entities/orders.yml",
    "entities/products.yml"
  ]
};

export const semanticLayer: SemanticLayer = {
  entities: new Map(ENTITY_ENTRIES),
  catalog: CATALOG,
};
