/* SPDX-License-Identifier: Apache-2.0 */
export interface CloudflareBuildEntryOptions {
  configPath: string;
  rootDir: string;
  outputDir: string;
}

export interface CloudflareBuildRunOptions {
  configPath: string;
  rootDir: string;
  outputDir: string;
  entryPath: string;
}

export function generateCloudflareServerEntry(options: CloudflareBuildEntryOptions): string {
  const configPath = options.configPath.replace(/\\/g, "/");
  return `// Auto-generated by arivie build --target cloudflare
import arivieConfig from ${JSON.stringify(configPath)};
import { createArivieServer } from "@arivie/core/server";
import { defineArivie } from "@arivie/core";

function isArivieInstance(value) {
  return value != null && typeof value === "object" && typeof value.handler === "function" && value.mastra != null;
}

const rootDir = process.env.ARIVIE_ROOT_DIR ?? ${JSON.stringify(options.rootDir)};
const instance = isArivieInstance(arivieConfig) ? arivieConfig : await defineArivie(arivieConfig);
const { app } = await createArivieServer(instance, { rootDir });

export default {
  async fetch(request, env, executionCtx) {
    return app.fetch(request, env, executionCtx);
  },
};
`;
}

export async function buildCloudflareServer(options: CloudflareBuildRunOptions): Promise<void> {
  const { build } = await import("vite");
  await build({
    root: options.rootDir,
    build: {
      lib: {
        entry: options.entryPath,
        formats: ["es"],
        fileName: () => "worker.mjs",
      },
      outDir: options.outputDir,
      emptyOutDir: false,
      rollupOptions: {
        output: {
          format: "es",
          entryFileNames: "worker.mjs",
        },
      },
    },
    resolve: {
      conditions: ["worker", "node"],
    },
  });
}
