/* SPDX-License-Identifier: Apache-2.0 */
import { isAbsolute, resolve } from "node:path";
import type { InlineConfig, Rollup } from "vite";

export interface NodeBuildEntryOptions {
  configPath: string;
  rootDir: string;
  outputDir: string;
}

export interface NodeBuildRunOptions {
  configPath: string;
  rootDir: string;
  outputDir: string;
  entryPath: string;
}

export function generateNodeServerEntry(options: NodeBuildEntryOptions): string {
  const configPath = options.configPath.replace(/\\/g, "/");
  const rootDir = options.rootDir.replace(/\\/g, "/");
  const outputDir = options.outputDir.replace(/\\/g, "/");

  return `// Auto-generated by arivie build --target node
import arivieConfig from ${JSON.stringify(configPath)};
import { createArivieServer } from "@arivie/core/server";
import { defineArivie } from "@arivie/core";
import { serve } from "@hono/node-server";

function isArivieApp(value) {
  return value != null && typeof value === "object" && typeof value.handler === "function" && value.sessions != null;
}

const rootDir = process.env.ARIVIE_ROOT_DIR ?? ${JSON.stringify(rootDir)};
const instance = isArivieApp(arivieConfig)
  ? arivieConfig
  : await defineArivie(arivieConfig);

const { app } = await createArivieServer(instance, { rootDir });

const port = parseInt(process.env.PORT ?? "3000", 10);
serve({ fetch: app.fetch.bind(app), port });
console.log(\`[arivie] Server listening on http://localhost:\${port}\`);
`;
}

export async function buildNodeServer(options: NodeBuildRunOptions): Promise<void> {
  const { build } = await import("vite");
  const absEntry = isAbsolute(options.entryPath)
    ? options.entryPath
    : resolve(options.rootDir, options.entryPath);

  const config: InlineConfig = {
    root: options.rootDir,
    build: {
      ssr: absEntry,
      target: "node20",
      outDir: options.outputDir,
      emptyOutDir: false,
      rollupOptions: {
        input: absEntry,
        output: {
          format: "es",
          entryFileNames: "server.mjs",
        },
      },
    },
    resolve: {
      conditions: ["node"],
    },
    define: {
      "import.meta.url": "import.meta.url",
    },
  };

  await build(config);
}
