/* SPDX-License-Identifier: Apache-2.0 */
/**
 * Deterministic generator for the sem-60 fixture (60 entities, >80k tokens).
 * Run from arivie/: tsx packages/agent/test/fixtures/gen-large.ts
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const outDir = join(dirname(fileURLToPath(import.meta.url)), "sem-60");
const entitiesDir = join(outDir, "entities");

function pad(n: number, width: number): string {
  return String(n).padStart(width, "0");
}

function descriptionBlock(index: number): string {
  const lines: string[] = [
    `Synthetic entity ${index} for auto-detect rag-mode threshold testing.`,
    `This paragraph is repeated with a stable index suffix so token totals exceed 80k across 60 entities.`,
  ];
  for (let line = 0; line < 44; line += 1) {
    lines.push(
      `Line ${line + 1}: entity_${pad(index, 2)} documents measure ${(line % 3) + 1}, dimension ${(line % 3) + 1}, and reporting grain for analytics agents.`,
    );
  }
  return lines.join("\n");
}

function entityYaml(index: number): string {
  const name = `entity_${pad(index, 2)}`;
  const desc = descriptionBlock(index);
  return `name: ${name}
description: |
${desc
  .split("\n")
  .map((line) => `  ${line}`)
  .join("\n")}

grain: one row per ${name}
primary_key: id

measures:
  - name: metric_a
    description: Primary aggregate for ${name}.
    sql: "SUM(amount_a)"
  - name: metric_b
    description: Secondary aggregate for ${name}.
    sql: "SUM(amount_b)"
  - name: metric_c
    description: Tertiary aggregate for ${name}.
    sql: "COUNT(*)"

dimensions:
  - name: status
    sql: status
    values: [open, closed, pending]
    description: Status dimension for ${name}.
  - name: created_at
    sql: created_at
    type: timestamp
    description: Created timestamp for ${name}.
  - name: region
    sql: region
    description: Region dimension for ${name}.

example_queries:
  - question: "Total metric_a for ${name} this quarter"
    sql: |
      SELECT SUM(amount_a) AS metric_a
      FROM ${name}
      WHERE created_at >= date_trunc('quarter', CURRENT_DATE)
  - question: "Count rows in ${name} by status"
    sql: |
      SELECT status, COUNT(*) AS row_count
      FROM ${name}
      GROUP BY status
`;
}

function catalogYaml(): string {
  const names = Array.from({ length: 60 }, (_, i) => `entity_${pad(i + 1, 2)}`);
  const entityLines = names
    .map(
      (name) => `  - name: ${name}
    description: Synthetic entity for rag-mode fixture.
    keywords: [${name}]`,
    )
    .join("\n");
  const sourceFiles = names
    .map((name) => `  - entities/${name}.yml`)
    .join("\n");

  return `entities:
${entityLines}
generated_at: "2026-05-20T00:00:00.000Z"
source_files:
${sourceFiles}
`;
}

mkdirSync(entitiesDir, { recursive: true });

for (let i = 1; i <= 60; i += 1) {
  const fileName = `entity_${pad(i, 2)}.yml`;
  const header =
    "# Generated by gen-large.ts (deterministic). Re-run to regenerate.\n";
  writeFileSync(join(entitiesDir, fileName), header + entityYaml(i), "utf8");
}

writeFileSync(
  join(outDir, "catalog.yml"),
  "# Generated by gen-large.ts (deterministic). Re-run to regenerate.\n" +
    catalogYaml(),
  "utf8",
);

console.log(`Wrote 60 entities + catalog to ${outDir}`);
