/* SPDX-License-Identifier: Apache-2.0 */

export type WooCommerceOrder = Record<string, unknown> & {
  id: number;
  parent_id: number;
  number: string;
  order_key: string;
  status: string;
  currency: string;
  date_created: string;
  date_modified: string;
  customer_id: number;
  billing: Record<string, unknown>;
  shipping: Record<string, unknown>;
  line_items: Array<Record<string, unknown>>;
  tax_lines: Array<Record<string, unknown>>;
  shipping_lines: Array<Record<string, unknown>>;
  fee_lines: Array<Record<string, unknown>>;
  coupon_lines: Array<Record<string, unknown>>;
  refunds: Array<Record<string, unknown>>;
  meta_data: Array<Record<string, unknown>>;
};

const billingAva = {
  first_name: "Ava",
  last_name: "Patel",
  company: "",
  address_1: "18 Market Street",
  address_2: "Apt 4B",
  city: "Austin",
  state: "TX",
  postcode: "78701",
  country: "US",
  email: "ava.patel@example.com",
  phone: "+1 512 555 0142",
};

const shippingAva = {
  first_name: "Ava",
  last_name: "Patel",
  company: "",
  address_1: "18 Market Street",
  address_2: "Apt 4B",
  city: "Austin",
  state: "TX",
  postcode: "78701",
  country: "US",
};

export const sampleOrders: WooCommerceOrder[] = [
  {
    id: 9812,
    parent_id: 0,
    number: "9812",
    order_key: "wc_order_r7XQzRKV4m2hA",
    created_via: "checkout",
    version: "8.9.3",
    status: "completed",
    currency: "USD",
    date_created: "2026-05-03T14:22:11",
    date_created_gmt: "2026-05-03T19:22:11",
    date_modified: "2026-05-03T14:51:08",
    date_modified_gmt: "2026-05-03T19:51:08",
    discount_total: "15.00",
    discount_tax: "1.24",
    shipping_total: "8.00",
    shipping_tax: "0.66",
    cart_tax: "7.82",
    total: "119.48",
    total_tax: "8.48",
    prices_include_tax: false,
    customer_id: 42,
    customer_ip_address: "198.51.100.24",
    customer_user_agent: "Mozilla/5.0 WooCommerce Demo Browser",
    customer_note: "Leave package at front desk.",
    billing: billingAva,
    shipping: shippingAva,
    payment_method: "stripe",
    payment_method_title: "Credit Card (Stripe)",
    transaction_id: "ch_3R8demoAva9812",
    date_paid: "2026-05-03T14:24:03",
    date_paid_gmt: "2026-05-03T19:24:03",
    date_completed: "2026-05-03T14:51:08",
    date_completed_gmt: "2026-05-03T19:51:08",
    cart_hash: "7df6d52b8ad4f18b51f0edc8b88c9812",
    meta_data: [
      { id: 21001, key: "_utm_source", value: "newsletter" },
      { id: 21002, key: "_warehouse", value: "AUS-01" },
    ],
    line_items: [
      {
        id: 31001,
        name: "Everyday Tee - Navy / M",
        product_id: 501,
        variation_id: 1501,
        quantity: 2,
        tax_class: "",
        subtotal: "70.00",
        subtotal_tax: "5.78",
        total: "60.00",
        total_tax: "4.96",
        taxes: [{ id: 7, total: "4.96", subtotal: "5.78" }],
        meta_data: [
          { id: 41001, key: "pa_color", value: "navy", display_key: "Color", display_value: "Navy" },
          { id: 41002, key: "pa_size", value: "m", display_key: "Size", display_value: "M" },
        ],
        sku: "TEE-NAVY-M",
        price: 30,
        image: { id: 9001, src: "https://store.example.com/wp-content/uploads/tee-navy.jpg" },
        parent_name: "Everyday Tee",
      },
      {
        id: 31002,
        name: "Ceramic Mug",
        product_id: 601,
        variation_id: 0,
        quantity: 1,
        tax_class: "",
        subtotal: "25.00",
        subtotal_tax: "2.07",
        total: "25.00",
        total_tax: "2.07",
        taxes: [{ id: 7, total: "2.07", subtotal: "2.07" }],
        meta_data: [{ id: 41003, key: "_gift_wrap", value: "yes", display_key: "Gift wrap", display_value: "Yes" }],
        sku: "MUG-CERAMIC",
        price: 25,
        image: { id: 9002, src: "https://store.example.com/wp-content/uploads/mug.jpg" },
        parent_name: null,
      },
    ],
    tax_lines: [
      { id: 51001, rate_code: "US-TX-STATE TAX", rate_id: 7, label: "TX Sales Tax", compound: false, tax_total: "7.03", shipping_tax_total: "0.66", rate_percent: 8.25, meta_data: [] },
    ],
    shipping_lines: [
      { id: 61001, method_title: "Flat rate", method_id: "flat_rate", instance_id: "3", total: "8.00", total_tax: "0.66", taxes: [{ id: 7, total: "0.66", subtotal: "" }], meta_data: [{ id: 61011, key: "Items", value: "Everyday Tee × 2, Ceramic Mug × 1", display_key: "Items", display_value: "Everyday Tee × 2, Ceramic Mug × 1" }] },
    ],
    fee_lines: [
      { id: 71001, name: "Rush handling", tax_class: "", tax_status: "taxable", total: "3.00", total_tax: "0.25", taxes: [{ id: 7, total: "0.25", subtotal: "" }], meta_data: [] },
    ],
    coupon_lines: [
      { id: 81001, code: "SPRING15", discount: "15.00", discount_tax: "1.24", meta_data: [{ id: 81011, key: "coupon_data", value: { discount_type: "fixed_cart", amount: "15" } }] },
    ],
    refunds: [],
    _links: {
      self: [{ href: "https://store.example.com/wp-json/wc/v3/orders/9812" }],
      collection: [{ href: "https://store.example.com/wp-json/wc/v3/orders" }],
      customer: [{ href: "https://store.example.com/wp-json/wc/v3/customers/42" }],
    },
  },
  {
    id: 9813,
    parent_id: 0,
    number: "9813",
    order_key: "wc_order_q6DemoKey9813",
    created_via: "checkout",
    version: "8.9.3",
    status: "processing",
    currency: "USD",
    date_created: "2026-05-09T09:15:00",
    date_created_gmt: "2026-05-09T14:15:00",
    date_modified: "2026-05-09T09:17:44",
    date_modified_gmt: "2026-05-09T14:17:44",
    discount_total: "0.00",
    discount_tax: "0.00",
    shipping_total: "0.00",
    shipping_tax: "0.00",
    cart_tax: "4.33",
    total: "56.83",
    total_tax: "4.33",
    prices_include_tax: false,
    customer_id: 84,
    customer_ip_address: "203.0.113.10",
    customer_user_agent: "Mozilla/5.0 WooCommerce Demo Browser",
    customer_note: "",
    billing: { first_name: "Mateo", last_name: "Rivera", company: "Studio Rivera", address_1: "44 Lake Road", address_2: "", city: "Madison", state: "WI", postcode: "53703", country: "US", email: "mateo.rivera@example.com", phone: "+1 608 555 0100" },
    shipping: { first_name: "Mateo", last_name: "Rivera", company: "Studio Rivera", address_1: "44 Lake Road", address_2: "", city: "Madison", state: "WI", postcode: "53703", country: "US" },
    payment_method: "paypal",
    payment_method_title: "PayPal",
    transaction_id: "PAYID-MATEO9813",
    date_paid: "2026-05-09T09:17:44",
    date_paid_gmt: "2026-05-09T14:17:44",
    date_completed: null,
    date_completed_gmt: null,
    cart_hash: "4ed3cfcb2b750a9813",
    meta_data: [{ id: 21003, key: "_source_channel", value: "organic-search" }],
    line_items: [
      { id: 31003, name: "Notebook Set", product_id: 701, variation_id: 0, quantity: 3, tax_class: "", subtotal: "52.50", subtotal_tax: "4.33", total: "52.50", total_tax: "4.33", taxes: [{ id: 7, total: "4.33", subtotal: "4.33" }], meta_data: [], sku: "NOTEBOOK-SET", price: 17.5, image: { id: 9003, src: "https://store.example.com/wp-content/uploads/notebooks.jpg" }, parent_name: null },
    ],
    tax_lines: [{ id: 51002, rate_code: "US-WI-STATE TAX", rate_id: 8, label: "WI Sales Tax", compound: false, tax_total: "4.33", shipping_tax_total: "0.00", rate_percent: 8.25, meta_data: [] }],
    shipping_lines: [{ id: 61002, method_title: "Free shipping", method_id: "free_shipping", instance_id: "5", total: "0.00", total_tax: "0.00", taxes: [], meta_data: [] }],
    fee_lines: [],
    coupon_lines: [],
    refunds: [],
    _links: { self: [{ href: "https://store.example.com/wp-json/wc/v3/orders/9813" }], collection: [{ href: "https://store.example.com/wp-json/wc/v3/orders" }], customer: [{ href: "https://store.example.com/wp-json/wc/v3/customers/84" }] },
  },
  {
    id: 9814,
    parent_id: 0,
    number: "9814",
    order_key: "wc_order_refundDemo9814",
    created_via: "checkout",
    version: "8.9.3",
    status: "refunded",
    currency: "USD",
    date_created: "2026-04-21T16:48:10",
    date_created_gmt: "2026-04-21T21:48:10",
    date_modified: "2026-05-11T10:03:22",
    date_modified_gmt: "2026-05-11T15:03:22",
    discount_total: "20.00",
    discount_tax: "1.65",
    shipping_total: "12.00",
    shipping_tax: "0.99",
    cart_tax: "13.20",
    total: "164.54",
    total_tax: "14.19",
    prices_include_tax: false,
    customer_id: 42,
    customer_ip_address: "198.51.100.24",
    customer_user_agent: "Mozilla/5.0 WooCommerce Demo Browser",
    customer_note: "Exchange requested if size is wrong.",
    billing: billingAva,
    shipping: shippingAva,
    payment_method: "stripe",
    payment_method_title: "Credit Card (Stripe)",
    transaction_id: "ch_3R8demoAva9814",
    date_paid: "2026-04-21T16:50:01",
    date_paid_gmt: "2026-04-21T21:50:01",
    date_completed: "2026-04-22T11:11:00",
    date_completed_gmt: "2026-04-22T16:11:00",
    cart_hash: "8bb28f3b9814",
    meta_data: [{ id: 21004, key: "_return_window_days", value: 30 }],
    line_items: [
      { id: 31004, name: "Hoodie - Heather / L", product_id: 801, variation_id: 1801, quantity: 1, tax_class: "", subtotal: "80.00", subtotal_tax: "6.60", total: "70.00", total_tax: "5.78", taxes: [{ id: 7, total: "5.78", subtotal: "6.60" }], meta_data: [{ id: 41004, key: "pa_color", value: "heather", display_key: "Color", display_value: "Heather" }, { id: 41005, key: "pa_size", value: "l", display_key: "Size", display_value: "L" }], sku: "HOOD-HEATHER-L", price: 70, image: { id: 9004, src: "https://store.example.com/wp-content/uploads/hoodie-heather.jpg" }, parent_name: "Hoodie" },
      { id: 31005, name: "Hoodie - Black / M", product_id: 801, variation_id: 1802, quantity: 1, tax_class: "", subtotal: "80.00", subtotal_tax: "6.60", total: "70.00", total_tax: "5.78", taxes: [{ id: 7, total: "5.78", subtotal: "6.60" }], meta_data: [{ id: 41006, key: "pa_color", value: "black", display_key: "Color", display_value: "Black" }, { id: 41007, key: "pa_size", value: "m", display_key: "Size", display_value: "M" }], sku: "HOOD-BLACK-M", price: 70, image: { id: 9005, src: "https://store.example.com/wp-content/uploads/hoodie-black.jpg" }, parent_name: "Hoodie" },
    ],
    tax_lines: [{ id: 51003, rate_code: "US-TX-STATE TAX", rate_id: 7, label: "TX Sales Tax", compound: false, tax_total: "11.55", shipping_tax_total: "0.99", rate_percent: 8.25, meta_data: [] }],
    shipping_lines: [{ id: 61003, method_title: "Priority mail", method_id: "flat_rate", instance_id: "4", total: "12.00", total_tax: "0.99", taxes: [{ id: 7, total: "0.99", subtotal: "" }], meta_data: [] }],
    fee_lines: [],
    coupon_lines: [{ id: 81002, code: "VIP20", discount: "20.00", discount_tax: "1.65", meta_data: [{ id: 81012, key: "coupon_data", value: { discount_type: "fixed_cart", amount: "20" } }] }],
    refunds: [{ id: 91001, reason: "Customer returned black hoodie", total: "-82.39" }],
    _links: { self: [{ href: "https://store.example.com/wp-json/wc/v3/orders/9814" }], collection: [{ href: "https://store.example.com/wp-json/wc/v3/orders" }], customer: [{ href: "https://store.example.com/wp-json/wc/v3/customers/42" }] },
  },
  {
    id: 9815,
    parent_id: 0,
    number: "9815",
    order_key: "wc_order_failedDemo9815",
    created_via: "checkout",
    version: "8.9.3",
    status: "failed",
    currency: "USD",
    date_created: "2026-05-15T20:08:01",
    date_created_gmt: "2026-05-16T01:08:01",
    date_modified: "2026-05-15T20:12:29",
    date_modified_gmt: "2026-05-16T01:12:29",
    discount_total: "0.00",
    discount_tax: "0.00",
    shipping_total: "6.00",
    shipping_tax: "0.50",
    cart_tax: "2.06",
    total: "33.56",
    total_tax: "2.56",
    prices_include_tax: false,
    customer_id: 0,
    customer_ip_address: "192.0.2.55",
    customer_user_agent: "Mozilla/5.0 WooCommerce Demo Browser",
    customer_note: "",
    billing: { first_name: "Guest", last_name: "Checkout", company: "", address_1: "9 Demo Lane", address_2: "", city: "Portland", state: "OR", postcode: "97205", country: "US", email: "guest.checkout@example.com", phone: "+1 503 555 0199" },
    shipping: { first_name: "Guest", last_name: "Checkout", company: "", address_1: "9 Demo Lane", address_2: "", city: "Portland", state: "OR", postcode: "97205", country: "US" },
    payment_method: "stripe",
    payment_method_title: "Credit Card (Stripe)",
    transaction_id: "",
    date_paid: null,
    date_paid_gmt: null,
    date_completed: null,
    date_completed_gmt: null,
    cart_hash: "failed9815",
    meta_data: [{ id: 21005, key: "_stripe_failure_code", value: "card_declined" }],
    line_items: [{ id: 31006, name: "Canvas Tote", product_id: 901, variation_id: 0, quantity: 1, tax_class: "", subtotal: "25.00", subtotal_tax: "2.06", total: "25.00", total_tax: "2.06", taxes: [{ id: 9, total: "2.06", subtotal: "2.06" }], meta_data: [], sku: "TOTE-CANVAS", price: 25, image: { id: 9006, src: "https://store.example.com/wp-content/uploads/tote.jpg" }, parent_name: null }],
    tax_lines: [{ id: 51004, rate_code: "US-OR-DEMO TAX", rate_id: 9, label: "Demo Tax", compound: false, tax_total: "2.06", shipping_tax_total: "0.50", rate_percent: 8.25, meta_data: [] }],
    shipping_lines: [{ id: 61004, method_title: "Flat rate", method_id: "flat_rate", instance_id: "3", total: "6.00", total_tax: "0.50", taxes: [{ id: 9, total: "0.50", subtotal: "" }], meta_data: [] }],
    fee_lines: [],
    coupon_lines: [],
    refunds: [],
    _links: { self: [{ href: "https://store.example.com/wp-json/wc/v3/orders/9815" }], collection: [{ href: "https://store.example.com/wp-json/wc/v3/orders" }] },
  },
  {
    id: 9816,
    parent_id: 0,
    number: "9816",
    order_key: "wc_order_cancelledDemo9816",
    created_via: "admin",
    version: "8.9.3",
    status: "cancelled",
    currency: "USD",
    date_created: "2026-05-18T08:31:45",
    date_created_gmt: "2026-05-18T13:31:45",
    date_modified: "2026-05-18T08:49:00",
    date_modified_gmt: "2026-05-18T13:49:00",
    discount_total: "5.00",
    discount_tax: "0.41",
    shipping_total: "5.00",
    shipping_tax: "0.41",
    cart_tax: "3.30",
    total: "43.71",
    total_tax: "3.71",
    prices_include_tax: false,
    customer_id: 105,
    customer_ip_address: "203.0.113.88",
    customer_user_agent: "Mozilla/5.0 WooCommerce Demo Browser",
    customer_note: "Cancelled before payment capture.",
    billing: { first_name: "Noor", last_name: "Chen", company: "", address_1: "77 King Street", address_2: "", city: "Toronto", state: "ON", postcode: "M5V 1K4", country: "CA", email: "noor.chen@example.ca", phone: "+1 416 555 0177" },
    shipping: { first_name: "Noor", last_name: "Chen", company: "", address_1: "77 King Street", address_2: "", city: "Toronto", state: "ON", postcode: "M5V 1K4", country: "CA" },
    payment_method: "cod",
    payment_method_title: "Cash on delivery",
    transaction_id: "",
    date_paid: null,
    date_paid_gmt: null,
    date_completed: null,
    date_completed_gmt: null,
    cart_hash: "cancelled9816",
    meta_data: [{ id: 21006, key: "_cancelled_by", value: "customer" }],
    line_items: [{ id: 31007, name: "Everyday Tee - White / S", product_id: 501, variation_id: 1502, quantity: 1, tax_class: "", subtotal: "40.00", subtotal_tax: "3.30", total: "35.00", total_tax: "2.89", taxes: [{ id: 10, total: "2.89", subtotal: "3.30" }], meta_data: [{ id: 41008, key: "pa_color", value: "white", display_key: "Color", display_value: "White" }, { id: 41009, key: "pa_size", value: "s", display_key: "Size", display_value: "S" }], sku: "TEE-WHITE-S", price: 35, image: { id: 9007, src: "https://store.example.com/wp-content/uploads/tee-white.jpg" }, parent_name: "Everyday Tee" }],
    tax_lines: [{ id: 51005, rate_code: "CA-ON-HST", rate_id: 10, label: "ON HST", compound: false, tax_total: "2.89", shipping_tax_total: "0.41", rate_percent: 13, meta_data: [] }],
    shipping_lines: [{ id: 61005, method_title: "Local pickup", method_id: "local_pickup", instance_id: "7", total: "5.00", total_tax: "0.41", taxes: [{ id: 10, total: "0.41", subtotal: "" }], meta_data: [] }],
    fee_lines: [],
    coupon_lines: [{ id: 81003, code: "WELCOME5", discount: "5.00", discount_tax: "0.41", meta_data: [] }],
    refunds: [],
    _links: { self: [{ href: "https://store.example.com/wp-json/wc/v3/orders/9816" }], collection: [{ href: "https://store.example.com/wp-json/wc/v3/orders" }], customer: [{ href: "https://store.example.com/wp-json/wc/v3/customers/105" }] },
  },
];
