/* SPDX-License-Identifier: Apache-2.0 */
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { Entity, SemanticLayer } from "./types.js";

function toPascalCase(name: string): string {
  return name
    .split(/[_\s-]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function quoteLiteral(value: string): string {
  return `'${value.replace(/\\/g, "\\\\").replace(/'/g, "\\'")}'`;
}

function unionOrNever(values: readonly string[]): string {
  if (values.length === 0) return "never";
  return values.map(quoteLiteral).join(" | ");
}

function buildMeasureTypeExport(entity: Entity): string | null {
  const names = (entity.measures ?? []).map((m) => m.name);
  if (names.length === 0) return null;
  return `export type ${toPascalCase(entity.name)}Measure = ${unionOrNever(names)};`;
}

function buildDimensionTypeExport(entity: Entity): string | null {
  const names = (entity.dimensions ?? []).map((d) => d.name);
  if (names.length === 0) return null;
  return `export type ${toPascalCase(entity.name)}Dimension = ${unionOrNever(names)};`;
}

function buildSegmentTypeExport(entity: Entity): string | null {
  const names = (entity.segments ?? []).map((s) => s.name);
  if (names.length === 0) return null;
  return `export type ${toPascalCase(entity.name)}Segment = ${unionOrNever(names)};`;
}

function quoteKey(name: string): string {
  // Object-literal keys need double quotes (single-quote in PascalCase
  // identifiers would be syntactically odd in generated TS output).
  return `"${name.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function buildSemanticMap(entities: readonly Entity[]): string {
  if (entities.length === 0) {
    return [
      "export interface ArivieSemantic {",
      "  entities: Record<string, never>;",
      "}",
    ].join("\n");
  }
  const entries = entities
    .slice()
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((entity) => {
      const measures = unionOrNever((entity.measures ?? []).map((m) => m.name));
      const dimensions = unionOrNever((entity.dimensions ?? []).map((d) => d.name));
      const segments = unionOrNever((entity.segments ?? []).map((s) => s.name));
      return [
        `    ${quoteKey(entity.name)}: {`,
        `      measures: ${measures};`,
        `      dimensions: ${dimensions};`,
        `      segments: ${segments};`,
        `    };`,
      ].join("\n");
    });
  return [
    "export interface ArivieSemantic {",
    "  entities: {",
    entries.join("\n"),
    "  };",
    "}",
  ].join("\n");
}

export function renderGeneratedIndex(layer: SemanticLayer): string {
  const entityNames = [...layer.entities.keys()].sort();
  const entities = entityNames
    .map((name) => layer.entities.get(name))
    .filter((entity): entity is Entity => entity != null);
  const timestamp = new Date().toISOString();
  const entityNamesLiteral = entityNames.map(quoteLiteral).join(", ");

  const measureExports = entities
    .map(buildMeasureTypeExport)
    .filter((line): line is string => line != null);
  const dimensionExports = entities
    .map(buildDimensionTypeExport)
    .filter((line): line is string => line != null);
  const segmentExports = entities
    .map(buildSegmentTypeExport)
    .filter((line): line is string => line != null);

  const lines = [
    "// @generated by @arivie/semantic from semantic/entities/*.yml. Do not edit.",
    `// Generated at: ${timestamp}`,
    "",
    `export const entityNames = [${entityNamesLiteral}] as const;`,
    "export type EntityName = (typeof entityNames)[number];",
    "",
    ...(measureExports.length > 0 ? [...measureExports, ""] : []),
    ...(dimensionExports.length > 0 ? [...dimensionExports, ""] : []),
    ...(segmentExports.length > 0 ? [...segmentExports, ""] : []),
    buildSemanticMap(entities),
    "",
  ];

  return lines.join("\n");
}

export async function codegen(
  layer: SemanticLayer,
  outDir: string,
): Promise<void> {
  const generatedDir = join(outDir, ".generated");
  await mkdir(generatedDir, { recursive: true });
  const content = renderGeneratedIndex(layer);
  await writeFile(join(generatedDir, "index.ts"), content, "utf8");
}
