/* SPDX-License-Identifier: Apache-2.0 */
/**
 * Inline the semantic layer at build time.
 *
 * Why: Cloudflare Workers (even with `nodejs_compat`) do not expose the
 * example's `semantic/` directory at runtime. Calling `loadSemanticLayerSync`
 * inside `getArivieRuntime()` from a Worker / Durable Object throws ENOENT on
 * the first request. We avoid that by parsing the YAML on the build host (this
 * Node script) and emitting `src/semantic-inline.ts`, which the runtime imports
 * as a plain ES module — no filesystem access at request time.
 *
 * This script is the only consumer of `node:fs` for the CF DO example. Re-run
 * via `pnpm --filter with-cloudflare-do build` (the `prebuild` hook).
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { loadSemanticLayerSync } from "@arivie/semantic";

const __dirname = dirname(fileURLToPath(import.meta.url));
const exampleRoot = join(__dirname, "..");
const semanticPath = join(exampleRoot, "semantic");
const outPath = join(exampleRoot, "src", "semantic-inline.ts");

const layer = loadSemanticLayerSync(semanticPath);
const entitiesTuple = Array.from(layer.entities.entries());

const banner =
  "/* SPDX-License-Identifier: Apache-2.0 */\n" +
  "/* Auto-generated by scripts/inline-semantic.ts — do not edit by hand. */\n" +
  "/* Re-run via `pnpm --filter with-cloudflare-do build` (prebuild hook). */\n";

const body =
  `import type { Entity, Catalog, SemanticLayer } from "@arivie/semantic";\n\n` +
  `const ENTITY_ENTRIES: readonly (readonly [string, Entity])[] = ` +
  `${JSON.stringify(entitiesTuple, null, 2)} as const;\n\n` +
  `const CATALOG: Catalog = ${JSON.stringify(layer.catalog, null, 2)};\n\n` +
  `export const semanticLayer: SemanticLayer = {\n` +
  `  entities: new Map(ENTITY_ENTRIES),\n` +
  `  catalog: CATALOG,\n` +
  `};\n`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, banner + body, "utf8");

console.log(
  `[inline-semantic] wrote ${outPath} (${entitiesTuple.length} entities, catalog with ${layer.catalog.entities.length} entries)`,
);
